export enum InputSourceEnum {
    Any = 'Any',
    LeftHand = 'LeftHand',
    LeftElbow = 'LeftElbow',
    LeftShoulder = 'LeftShoulder',
    LeftKnee = 'LeftKnee',
    LeftFoot = 'LeftFoot',
    RightHand = 'RightHand',
    RightElbow = 'RightElbow',
    RightShoulder = 'RightShoulder',
    RightKnee = 'RightKnee',
    RightFoot = 'RightFoot',
    Head = 'Head',
    Chest = 'Chest',
    Waist = 'Waist',
    Gamepad = 'Gamepad',
    Stylus = 'Stylus',
    Keyboard = 'Keyboard',
    Camera = 'Camera',
    Treadmill = 'Treadmill',
}